### ISSUE TITLE
Save events doesn't work

### ISSUE THREAD

**Issue by hugolv89** [iionly/event_calendar#10]
When I try to add a new event and I click the save button, the page just reload.

I have installed the plugin and the suggested dependencies on a fresh installation of elgg 2.3.3 with  Apache/2.4.6 (CentOS) PHP/7.0.21.

Thank you for your attention to this matter.

**Comment by iionly** [comment]
The other plugins are only suggestions and no requirements. Do you still have the problem with only Event Calendar plugin enabled and the suggested plugins disabled? It seems I have broken the Event Poll plugin in the latest release though (calendar for event time not showing up anymore). Need to fix that. But that's only relevant when selecting to schedule a poll on creation of an event.

Have you set the Event Calendar plugin setting "Make all visible fields except long description required" to yes? It seems this option might be broken (or at least partly broken when the option "Hide fees, contact, organiser and long description fields" is also set to yes - possibly checking for input on disabled input fields - need to check that). But if a required input is missing there should be an error displayed on the top of the page about a missing input. Do you see such an error message?

I can't test on php 7 yet. I have only one development and test server where I currently still need php 5.6 to be able to keep Elgg test installations older than Elgg 2.3 running. So, the problem with the event saving not working might be an issue on php 7 only. Have you checked the error log on your server? Are there any errors logged at the time of saving an event that might explain what's wrong?

**Comment by hugolv89** [comment]
Hi, the problem persists without the suggested plugins. The only error displayed (javascript popup) occurs when I don't write the title (sometimes a "missing field error" is displayed when all fields are filled), but works fine when I disable the setting "Make all visible fields except long description required", even with the suggested plugins enabled.

On the other hand, the log doesn't seems to show anything related with the plugin when it's alone, but with the au_subgroups plugin, it happens.

`[Fri Jul 28 12:50:33.148296 2017] [:error] [pid 8896] [client 193.144.81.198:6655] WARNING: Deprecated in 2.3: Event [pagesetup, system] is deprecated. Use menu or page shell hooks. Called from [#9] /var/www/html/elgg233/vendor/elgg/elgg/engine/classes/Elgg/EventsService.php:64<br /> -> [#8] /var/www/html/elgg233/vendor/elgg/elgg/engine/lib/elgglib.php:551<br /> -> [#7] /var/www/html/elgg233/mod/au_subgroups/start.php:36, referer: http://domain/elgg233/event_calendar/add/`

Thank you for your prompt reply.

**Comment by iionly** [comment]
This log entry from the au_subgroups plugin is unrelated (it's just a warning for Elgg 2.3 telling you that if the plugin code is not updated it is very likely no longer working on newer versions of Elgg, i.e. Elgg 3 - actually I've made the corresponding fix for Event Calendar just with the latest 2.3.1 release).

Are you using the latest version of Event Calendar (version 2.3.1)? If not, please update before testing.

The on-screen error message telling you about missing input is telling you indeed that some input fields lack the required input (putting aside the "Make all visible fields except long description required" option that is indeed buggy and therefore I would recommend to not using this option at the moment). Have you entered at least event title, venue and selected a starting date before saving an event? If not, please re-test. If it still fails I would suggest to enter something for all visible fields just for testing at least if it makes a difference.

I thought you were testing with only the Event Calendar plugin as only 3rd party plugin. Please test it with any other 3rd party plugin at least temporarily disabled. As I already mentioned, I can't reproduce your issue so far. And in case you have some buggy other plugin enabled (maybe just not fully compatible with Elgg 2.3) it might cause the problem.

**Comment by iionly** [comment]
I've just released version 2.3.2 of the Event Calendar plugin and you might want to give it a try. I've found and fixed a few issues that might have caused the problem with saving events for you.
