### ISSUE TITLE
FR: Allow dynamic change of listing format

### ISSUE THREAD

**Issue by dploeger** [iionly/event_calendar#11]
We would like to offer multiple listing formats to the users of the page: One agenda view and one full view. Currently, the listing format is hard-coded via the plugin settings.

**Comment by iionly** [comment]
I'll take a lot at your pull request when working on the next release and I might add it then. I can't say at the moment when I will start working again on the Event Calendar plugin. I hope it won't be too far in the future (e.g. Elgg 3 compatible release also) but it might take some weeks at least as I want to finish the work I've started on some other plugins first.

**Comment by dploeger** [comment]
Thanks, yes. It's #12

**Comment by dploeger** [comment]
I've added title menu items to quickly switch between views now, too.

**Comment by iionly** [comment]
Implemented in version 2.3.4 and newer. I've done it slightly different than you but urls pattern is the same.
