### ISSUE TITLE
FR: Support Elgg >3

### ISSUE THREAD

**Issue by dploeger** [iionly/event_calendar#14]
I'm wondering, why nobody else created this issue. I need support of event_calendar for Elgg >3.

Any plans to support that or are there alternatives?

**Comment by iionly** [comment]
Yes, I want to upgrade all my plugins for Elgg 3. But I had no time at all for any coding for probably the last 6 months. So, any updated version of Event Calendar or any other of my plugins will be released when I have time (or someone else is faster). I don't know if anyone else might have updated the plugin already. Other option could be the Event Manager plugin from Coldtrick that is maybe already available for Elgg 3.

**Comment by dploeger** [comment]
Could you please leave this open? I'm already working on a pull request.

**Comment by iionly** [comment]
Okay. I hadn't understood your Intention top make an PR. Please do!

**Comment by dploeger** [comment]
I think, I'm at about 70% of completing it. I will open a PR once I'm through with the features we're using on our site.

If I may, I'll also open some FRs for optimizing the code, because I've come along a lot of code duplication and other stuff.

**Comment by dploeger** [comment]
Just FYI: I've also added  feature to toggle adding the Organizer field to ICS-exports, because we had issues where the organizer of the events got a load of "Accept" or "Decline" mails. ;-)

**Comment by iionly** [comment]
I've made a release for Elgg 3.X (and a second one for Elgg 3.3.X), so closing this.
