### ISSUE TITLE
Roles plugin cannot manage correctly event_calendar menus title permissions because of conflicting contexts

### ISSUE THREAD

**Issue by oseg** [iionly/event_calendar#2]
Hello,

A few words about my context: elgg v1.12, event_calendar v1.10.3
I am using "roles" framework plugin to manage my site content rights: 
my "default users" don't have rights to create groups (for instance)
After the installation of the event calendar plugin in "full view", I noticed that my "default users" didn't have rights to create group event calendar...

After a few investigations, I found the issue:
in event_calendar_get_page_content_list function, in the case of $page_type == 'group',
elgg_push_context('groups') is called before the call of elgg_register_title_button
Then "roles" plugin register hook cannot distinguish between 'groups' and 'event_calendar' menu:title because both are in the same 'groups' context 

I workaround the issue by replacing elgg_push_context('groups') by elgg_push_context('event_calendar')
I also noticed the lack of elgg_pop_context() in event_calendar_page_handler just after echo event_calendar_get_page_content_list($page_type, $group_guid, $start_date, $display_mode, $filter_mode, $region)

**Comment by iionly** [comment]
Should be fixed in version 2.3.1.
