### ISSUE TITLE
ical feeds for site calendar

### ISSUE THREAD

**Issue by dcrobertson01** [iionly/event_calendar#8]
Hi - not sure if this is a bug or a misconfiguration or just plain incompetence, but I cannot figure out what time zones are being used for the calendar ics exports.

I have the timezone in my elgg-config/settings file set to 
`date_default_timezone_set('Pacific/Auckland');`
Which is UTC +13 at the moment.

If I get the time zone and output it on a page (eg, the agenda-view), it is shown correctly

```
$timezone=date_default_timezone_get();
$html.= '<pre>'.$timezone.'</pre>';
```

I add an event that starts on the 25th December 2016 at 12:05 am and ends on the 25th December 2016 at 6:00 pm. Which is 24th December 2016 at 11:05 pm and 25th December 2016 5:00am UTC.

When I export the event with the ical button from the events page, or export the site wide calendar with the Export button, it all appears to be correct. 

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//https://my.domain.org/elgg-2.2.3///NONSGML kigkonsult.se i
 Calcreator 2.16.12//
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-TIMEZONE:Pacific/Auckland
X-WR-CALNAME:doncrCalendar
BEGIN:VTIMEZONE
TZID:Pacific/Auckland
BEGIN:STANDARD
DTSTART:20170402T030000
TZOFFSETFROM:+1300
TZOFFSETTO:+1200
TZNAME:NZST
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:20170924T020000
TZOFFSETFROM:+1200
TZOFFSETTO:+1300
TZNAME:NZDT
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
UID:20161221T125052NZDT-28712S0MmD@https://my.domain.org/elgg-2.2.3/
DTSTAMP:20161220T235052Z
DESCRIPTION:
DTSTART;TZID=Pacific/Auckland:20161225T000500
DTEND;TZID=Pacific/Auckland:20161225T180000
LOCATION:Halswell Domain
ORGANIZER;CN=Fred@rnet.org:MAILTO:don@my.domain.org
SUMMARY:test
X-PROP-REGION:
X-PROP-TYPE:
X-PROP-FEES:
X-PROP-TAGS:
X-PROP-CONTACT:
X-PROP-LONG-DESC:
END:VEVENT
END:VCALENDAR
```

But if I use the ical button on the event_calendar/list page, I get 

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Curverider Ltd//NONSGML Elgg 2.2.3//EN
BEGIN:VEVENT
UID:https://hcn.rnet.duckdns.org/elgg-2.2.3/event_calendar/view/73
URL:https://hcn.rnet.duckdns.org/elgg-2.2.3/event_calendar/view/73
DTSTAMP:20161221T123721Z
CREATED:20161220T210539Z
LAST-MODIFIED:20161221T123721Z
DTSTART:20161225T000500Z
DTEND:20161225T180000Z
SUMMARY:test
DESCRIPTION:
LOCATION:Halswell Domain
CATEGORIES:
END:VEVENT
END:VCALENDAR
```

Which is using the local time with a 'Z' to indicate UTC time. 

I have changed lines 33 and 35 from

```
DTSTART;VALUE=DATE:<?php echo date("Ymd\THis\Z", $event->start_date);  ?>

DTEND;VALUE=DATE:<?php echo date("Ymd\THis\Z", $event->real_end_time);  ?>
```
to 
```
DTSTART:<?php echo gmdate("Ymd\THis\Z", $event->start_date);  ?>

DTEND:<?php echo gmdate("Ymd\THis\Z", $event->real_end_time);  ?>
```

and think that solves the problem. VALUE=DATE should be used for all day events without a time. gmdate() formats a UTC date. date() formats a local date. I'm guessing that all the 'Z' dates should be using gmdate?

**Comment by iionly** [comment]
Thanks for reporting. I can't say anything about the issue yet. I'll have to test it myself and look into the code first. I hope I'll find some time at the beginning of next year for it.

**Comment by iionly** [comment]
Version 2.3.1 of Event Calendar should provide consistent results on exporting events.
